### ISSUE TITLE
Unknown Error: Position: Component: /word/fontTable.xml, line: 1, column: 320

### ISSUE THREAD

**Issue by ghost** [pjfanning/ooxml-strict-converter#3]
Created file cannot be opened.
![image](https://cloud.githubusercontent.com/assets/14043156/17998399/75effcb2-6b74-11e6-9cf1-d1f9289a672e.png)
Is this converter for XLSX only? Because only Excel-Documents are used in the code, But your description does not exclude MS-Word-Documents, and even if bug #57699 only concerns XSSF, XWPF is also affected.

**Comment by ghost** [comment]
This seems to be a problem in `/word/fontTable.xml`:
`w:fonts/w:font/w:sig`
The attribute values of this tag differ, and if they are changed, everything works just fine (concerning `/word/fontTable.xml`).
After this, problems show up which are affecting `word/numbering.xml line: 1, column: 0`. I was not yet able to spot any differences but attributes in some tags which differ in the order they appear.
E.g.:
`<w:tag w:attr1='val1' w:attr2='val2'>`
VS.
`<w:tag w:attr2='val2' w:attr1='val1'>`

**Comment by pjfanning** [comment]
Hi Tim,
This is just experimental code that I'm not currently planning to do much more with. I've only been testing xlsx files as those are what I'm working with. I don't have a requirement to read docx files.
If you could send me a sample docx file, I can have a quick look to see if I can add it to the test cases here.
It is the [ooxml-strict-mappings.properties](https://github.com/pjfanning/ooxml-strict-converter/blob/master/src/main/resources/ooxml-strict-mappings.properties) file that would probably need to have extra mappings added to it.
If you have time to experiment yourself, maybe you could fork this code and develop your own case and we can maybe merge changes later.
I am a Mac user and the Office version I have still doesn't support writing out Strict OOXML format docs.

**Comment by ghost** [comment]
I found a workaround for strict OOXML usage with my library (Apache POI), so I won't use this any more, sorry :/
